### ISSUE TITLE
Create Homebrew Cask

### ISSUE THREAD

**Issue by schwedenmut** [steve228uk/YouTube-Music#10]
To support your Youtube Music wrapper app, I hurried ahead to create a brew cask for the current version 1.0.3.  
Currently I created a pull request to be merged into the homebrew-cask repo at https://github.com/Homebrew/homebrew-cask. Hopefully you are consent with the integration into Homebrew.

**Comment by schwedenmut** [comment]
https://github.com/Homebrew/homebrew-cask/pull/49012

**Comment by steve228uk** [comment]
This is great, thank you! Feel free to submit a PR here adding instructions to the readme if you have the time 😊
