### ISSUE TITLE
Create an Automated Release Pipeline

### ISSUE THREAD

**Issue by TimOliver** [steve228uk/YouTube-Music#104]
It's been a while since this project had an official release. And certainly we can lower the barrier and complexity of uploading new releases by introducing an automated release pipeline.

GitHub Actions is an amazing utility for this, especially now that it's possible to manually trigger workflows with manual parameters, so a pipeline that goes through and bumps the versioning and everything is possible.

That being said, I _think_ all new releases need to be both signed and notarised by Apple, otherwise the current versions of macOS will identify them as "potential malware" and require a lot of extra effort to run. I'm happy to donate the certificates for my sole trader iOS developer program to support this, assuming no one else sees any potential risk in that.

So I guess next steps:

1. Get a new release out now, manual if need be.
2. Set up a new GitHub Action pipeline for automating releases.
3. Consider replacing `DevMateKit` with `Sparkle` to allow automatic updating (But I have no idea how easy this is)

**Comment by unbeatable-101** [comment]
> Consider replacing DevMateKit with Sparkle to allow automatic updating (But I have no idea how easy this is)

Sparkle can't auto-update when in a sandbox yet.

https://github.com/sparkle-project/Sparkle/issues/363

**Comment by TimOliver** [comment]
@unbeatable-101 Oh dear. Well spotted! I had no idea that was a limitation. :(

I just looked deeper into it. Apparently Sparkle 2.0 has auto-updating in a sandbox working. It's billed as still being in beta, but some apps have already started migrating to it.

I guess given the nature of this app is, we could certainly give Sparkle 2.0 a try and see if it fits the app's needs.

https://github.com/sparkle-project/Sparkle/tree/2.x

**Comment by TimOliver** [comment]
Okay! So it looks like Sparkle development has made some amazing progress with 2.0 and 1.0 has now entered legacy support status.

I'm still working out the pipeline, but I hope I can have something to show soon. :)

**Comment by TimOliver** [comment]
Done. 😁 It's not perfect yet (I'm still finding formatting bugs here and there), but I'll keep refining it as I go.
