### ISSUE TITLE
[M1] [MBP] [11.1] Using too much CPU while playing songs

### ISSUE THREAD

**Issue by pranz29** [steve228uk/YouTube-Music#107]
Steps to reproduce :

1. Do a clean app install.
2. Login!
3. Try to play a long music file. (10 min+).
4. The CPU usage should spike to about 50%.

This must be lower than or equal to what used to be on a 2015 i5 MBa. But seems like it's about twice that.

**Comment by shaunsingh** [comment]
I recently received my m1 MacBook Pro (16gb of ram), latest os, with a fresh install of yt music

I loaded a long music file of about 15 minutes, and usage is hovering around 4%. Is the issue still there?

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/71196912/102703925-6afade80-4243-11eb-8974-68f5fe48d5e1.png">

**Comment by pranz29** [comment]
Seems like its gone now! Some how the window server was causing issues.
