### ISSUE TITLE
Next and Previous media keys unresponsive on keyboard and Touch Bar (M1 MacBook Pro)

### ISSUE THREAD

**Issue by timotealion** [steve228uk/YouTube-Music#119]
Play/Pause works with focus and no focus.
Command -> and Command <- works with focus

**Comment by eaigner** [comment]
Same issue, M1 Mac mini.

**Comment by Tolmark12** [comment]
Any thoughts on how to fix this?

**Comment by justAsascha** [comment]
Same on MBP 16" (intel)

**Comment by berkantaras** [comment]
I am looking forward to having this problem resolved (M1 Air)

**Comment by dantnad** [comment]
Same, Intel 13" MBP 2019

**Comment by harryfear** [comment]
Same on 16" MBP

**Comment by yj990315** [comment]
same MacBook m1 air

**Comment by ivogonzalvez** [comment]
Same here 15" MBP (Mac OS Catalina)

**Comment by timotealion** [comment]
Based on all the different configurations of Macs reported here, did it ever work?

**Comment by TimOliver** [comment]
This is a duplicate of #33 so I'm going to close this issue in favour of continuing the discussion there. Thanks! :)
