### ISSUE TITLE
Icon Improvement Request - Should follow Macos Icon Guidelines

### ISSUE THREAD

**Issue by masbaehr** [steve228uk/YouTube-Music#155]
I think the icon should be reworked slightly to fit in MacOS Monterey

https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/

Now the icons is a bit bigger than others, and does not have the square
![image](https://user-images.githubusercontent.com/38694044/151527472-f6d3eb9e-437e-4680-bafd-11a78196da8c.png)

Maybe a white square could help like done for the iPad App

**Comment by TimOliver** [comment]
Hi @masbaehr! Oh yes. This has been a bit of an eye sore I've been meaning to fix.

I might see if I can do it this weekend! :)

**Comment by TimOliver** [comment]
How's this?

![Icon-MacOS-512x512@2x](https://user-images.githubusercontent.com/429119/153883884-9a98eb38-f9db-4864-b59d-d064934f2c08.png)

**Comment by masbaehr** [comment]
Looks good :D - The iOS icon does not have the shadows but to be honest i don't know if you are allowed to copy it 1:1 anyway. 

 
![image](https://user-images.githubusercontent.com/38694044/153887100-c049dd00-1769-4e9b-a999-6e503471dcc2.png)

**Comment by TimOliver** [comment]
Thanks! Yep, that's correct. Big Sur iconography has a different design language to iOS, so I took some design cues from how Google is adapting the Google Chrome app icon and applied them here.

![](https://pbs.twimg.com/media/FKw9GwOVQAIzgOv?format=jpg&name=medium)

[I lived streamed the whole process](https://www.youtube.com/watch?v=fEAteG8i2E8 ) if you want to see how I made it. :D

**Comment by masbaehr** [comment]
Nice work! Interesting to see how you done it. Is there a way to build without having to do the process with the Apple Dev Account?
Or can you maybe build a beta i can test? Thanks

**Comment by TimOliver** [comment]
Yep! You can apply it to your current copy of YT Music as a custom icon. Just download that image above. :)

Here's how to apply it: https://9to5mac.com/2021/11/08/change-mac-icons/amp/

**Comment by domoritz** [comment]
I think this has been fixed, right?

**Comment by TimOliver** [comment]
I think so. I went through a few more iterations in the end after the official Chrome update launched and I was able to compare it pixel for pixel, and that one's the one that's live in here now.

I guess if anyone else has any more suggestions for improving the icon, we can talk about it in a new issue. Thanks!
