### ISSUE TITLE
Search box is now part of the title bar, causing issues with selecting text via mouse

### ISSUE THREAD

**Issue by jscheel** [steve228uk/YouTube-Music#161]
If you try to double click text in the search bar to select all, it maximizes the window. If you try to drag-select text, it moves the app window. I'm guessing this came from https://github.com/steve228uk/YouTube-Music/pull/151

**Comment by TimOliver** [comment]
Oh no. Yeah that sounds like that other PR introduced a regression. 😅

Should we revert?

/cc @atom2ueki

**Comment by atom2ueki** [comment]
Sorry hear about this, yes, I've noticed this as well (after PR merged) as there is no way to split this search view over the main one or I didn't found a better solution, for now have to either give up double click maximum the view or double click select all, surely can revert this part.

**Comment by atom2ueki** [comment]
@jscheel @TimOliver 
https://github.com/steve228uk/YouTube-Music/blob/ad51b3ad98779e31cc73940597c6eac1b2ed1dfb/YT%20Music/Controllers/ViewController.swift#L81

https://github.com/steve228uk/YouTube-Music/blob/ad51b3ad98779e31cc73940597c6eac1b2ed1dfb/YT%20Music/Controllers/ViewController.swift#L154

these 2 places previously was 20, when it increased to 64, NSView action will take a higher priority, I will raise a PR revert it back later

**Comment by atom2ueki** [comment]
@TimOliver Shall we close this ticket?

**Comment by TimOliver** [comment]
Sounds good. :)
