### ISSUE TITLE
mac release for 1.0.4

### ISSUE THREAD

**Issue by brianmorton** [steve228uk/YouTube-Music#17]
will there be one?

**Comment by steve228uk** [comment]
This is available from the link on the Readme or the releases page.

**Comment by brianmorton** [comment]
I am a contrib for homebrew and I'm just trying to keep this updated.

If it makes more sense for you, I can change our appcast feed to be the one from devmate (`https://updates.devmate.com/uk.co.wearecocoon.YT-Music.xml`) as that seems to have the 1.0.4 release.

Thoughts?

**Comment by steve228uk** [comment]
Oh my apologies, I meant to upload the .app here. The devmate appcast is likely the best thing here.

**Comment by brianmorton** [comment]
Thanks and no worries - I have submitted a PR to change the appcast and download URLs to be from devmate :)
