### ISSUE TITLE
Can we please have a 'repeat' button

### ISSUE THREAD

**Issue by patilswapnilv** [steve228uk/YouTube-Music#175]
So I listen to certain songs on repeat mode sometimes. Just discovered this app. Love the interface. Thank you very much for making this. 

But can we please have a 'repeat' button?

**Comment by maxhgerlach** [comment]
![image](https://user-images.githubusercontent.com/1778667/195613420-58ef415d-7723-44eb-acbb-3a116174ee3e.png)

Isn't it right there between volume and shuffle?

**Comment by michaelwills** [comment]
New user's might not immediately notice it's there when you hover over it. It is there though @patilswapnilv

![CleanShot 2022-11-01 at 13 10 47](https://user-images.githubusercontent.com/196266/199163681-5566641c-b63c-45e4-af67-a962af43b7cb.gif)

**Comment by patilswapnilv** [comment]
Hey @michaelwills,

Thanks a lot for pointing it out. 
I missed it; my bad 

The app works great! Keep up the good work 🚀
