### ISSUE TITLE
DockMenu: play, next and previous action

### ISSUE THREAD

**Issue by MrDyro** [steve228uk/YouTube-Music#18]
Hi,

It would be nice to have the ability to skip a song from the dock menu.  I'm not a fan of the media keys ;)

Something like this:

<img width="196" alt="screen shot 2018-07-03 at 13 07 34" src="https://user-images.githubusercontent.com/1315442/42216448-1f09f390-7ec2-11e8-84ca-4827ebf9f7e1.png">

**Comment by steve228uk** [comment]
These have been merged into the master branch. Still to add are:

- Seek Forward
- Seek Backward
- Shuffle
- Repeat

New observations will also need to be added to `observer.js` for the shuffle and repeat actions.

**Comment by steve228uk** [comment]
Added to v1.0.5
