### ISSUE TITLE
Media Key Support

### ISSUE THREAD

**Issue by steve228uk** [steve228uk/YouTube-Music#2]
Unfortunately due to WKWebView seemingly not wanting to work outside of a sandbox media key support has not been possible 😟 

I'm still searching for a work around but if anyone knows of one it would be much appreciated.

**Comment by nicolinuxfr** [comment]
It works by default on High Sierra, as it works with the website opened in Safari.

**Comment by steve228uk** [comment]
@nicolinuxfr Interesting… I've not managed to get it to work. You on a TouchBar mac?

**Comment by nicolinuxfr** [comment]
Nope… It was a change in High Sierra, by default the media keys control the app last used for media, including the browser. I don't think there's a setting for that either…

**Comment by steve228uk** [comment]
@nicolinuxfr Ah cool! I've added in manual capture just in case as this also works on 10.12.
