### ISSUE TITLE
Add user notifications

### ISSUE THREAD

**Issue by steve228uk** [steve228uk/YouTube-Music#20]
It might be nice to add user notifications when the track changes.

**Comment by steve228uk** [comment]
Added. Will be released in 1.0.5 shortly

**Comment by eblanchette** [comment]
Is this optional?

**Comment by daijiang** [comment]
Can you make the notification optional?? I cannot find a way to turn the notification off...

**Comment by steve228uk** [comment]
@daijiang @eblanchette Like all notifications on macOS this can be turned of in System Preferences > Notifications.

**Comment by daijiang** [comment]
Thanks!
