### ISSUE TITLE
Populate MPNowPlayingMediaCenter

### ISSUE THREAD

**Issue by carlosgj94** [steve228uk/YouTube-Music#21]
It would be nice to be able to pass to next/previous song through the touch bar, pretty much like Spotify or Apple Music do.

**Comment by steve228uk** [comment]
Thanks for reporting this. I'd assumed it would be available already but didn't test. I'll look into it further.

**Comment by carlosgj94** [comment]
Sorry I didn't provided more info. Here you have a couple of screenshots comparing the touchbar in YT Music VS Spotify.
YT Music:
<img width="1085" alt="touch bar shot 2018-07-04 at 20 53 19" src="https://user-images.githubusercontent.com/4912635/42291541-9bc707fa-7fcc-11e8-8949-b9ae101c2f55.png">
Spotify:
<img width="1085" alt="touch bar shot 2018-07-04 at 20 54 22" src="https://user-images.githubusercontent.com/4912635/42291550-aa97e2cc-7fcc-11e8-8b04-35a3a8b9969a.png">
As you can see, as you said I can control the music, but not as fluent as spotify where you can tap stop, next and previous.

Anyway, congrats, this is a pretty usable project 👍

**Comment by steve228uk** [comment]
@carlosgj94 I don't have a TouchBar MacBook to test this in but running it with the simulator I can see media controls in the command strip to the right. Are these accessible there for you?

**Comment by steve228uk** [comment]
<img width="1085" alt="touch bar shot 2018-07-05 at 14 55 49" src="https://user-images.githubusercontent.com/1169297/42327413-879c820e-8063-11e8-83cd-c12f0f60df4e.png">

It looks like Spotify implements a custom Touch Bar though I can't see the scrubber outlined in @carlosgj94's screenshot.

**Comment by steve228uk** [comment]
<img width="1085" alt="touch bar shot 2018-07-05 at 14 57 24" src="https://user-images.githubusercontent.com/1169297/42327531-d05526e0-8063-11e8-9b5c-d9690afe5345.png">

Ah, looks like it's the media centre. Going to look into `MPNowPlayingMediaCenter` support.

**Comment by steve228uk** [comment]
<img width="337" alt="screen shot 2018-07-10 at 16 00 48" src="https://user-images.githubusercontent.com/1169297/42518823-a52572f4-845a-11e8-93a6-c7230e4c1ae9.png">

Also affects the Today widget

**Comment by steve228uk** [comment]
I've added this to the main branch (seek support is not currently implemented). Are you able to test the attached build and let me know if this adds media controls to the Touch Bar @carlosgj94?

[YT Music.zip](https://github.com/steve228uk/YouTube-Music/files/2181324/YT.Music.zip)

**Comment by carlosgj94** [comment]
Awesome! Great job man! 👏 

<img width="1085" alt="image" src="https://user-images.githubusercontent.com/4912635/42533967-acdaf24a-848b-11e8-8f90-280ab7ca1a3f.png">

**Comment by steve228uk** [comment]
Thanks @carlosgj94!

Gonna leave this open until it's merged and seek support has been added.
