### ISSUE TITLE
Display currently playing song in menu bar

### ISSUE THREAD

**Issue by petebocken** [steve228uk/YouTube-Music#26]
Shot in the dark feature request.  I've used several apps that display the currently playing song & artist in the menu bar.  Would be pretty neat to be able to have the ability with this app.  Not sure if it's even possible.

**Comment by steve228uk** [comment]
@petebocken Do you have any examples of apps that do this? Now playing info is currently displayed in the Notification Centre Now Playing widget.

<img width="438" alt="screen shot 2018-07-15 at 00 09 58" src="https://user-images.githubusercontent.com/1169297/42729042-7eda5bfc-87c3-11e8-922f-ea1bc23cb692.png">

**Comment by petebocken** [comment]
There are lots of ones for iTunes and Spotify:

https://github.com/kmikiy/SpotMenu

https://github.com/serban/menubar-ticker

Wasn't sure if it was harder because you are basically doing a web wrapper, correct? However, if you can throw it in the notification center, maybe it's possible?

**Comment by petebocken** [comment]
That does make more sense.  Especially if you use more than one music app.  Thanks!
