### ISSUE TITLE
Add touchbar support

### ISSUE THREAD

**Issue by zlodes** [steve228uk/YouTube-Music#32]

**Comment by steve228uk** [comment]
Thanks for reporting @zlodes, are you able to let me know what needs adding that's not included in #21?

**Comment by zlodes** [comment]
@steve228uk oh, didn't see that. 
It would be cool for me if there was buttons for playback control like "back", "forward", "play/pause".

**Comment by maggo** [comment]
I just downloaded the app and I can see and use all media keys (default ones and the ones in the scrub bar) maybe you're on an old version?

Thanks Steve for this, it's exactly what was missing for the perfect YT music experience :)

**Comment by steve228uk** [comment]
Thanks for confirming @maggo! I'm going to close this issue for now then.
