### ISSUE TITLE
Mobile size window

### ISSUE THREAD

**Issue by PascalPixel** [steve228uk/YouTube-Music#50]
@steve228uk love the app! Have a request: would it be possible to reduce the minimal window width and height? YT music has a good mobile layout and it would make it a little less large on the desktop. I tried doing it myself by can't get the cocoapods dependencies to resolve properly...

**Comment by jordyvandomselaar** [comment]
It already uses the mobile layout?
![image](https://user-images.githubusercontent.com/12712484/54610660-bde3a880-4a55-11e9-9dda-a7da586e1b07.png)

**Comment by Superpencil** [comment]
<img width="453" alt="Screen Shot 2019-03-20 at 11 14 11" src="https://user-images.githubusercontent.com/3094044/54654364-51be7e80-4b01-11e9-967f-01359417c7fe.png">

Yes it is, and it can even go smaller without problems, here is an example of YouTube Music in the Min browser at an 'iPhone 4' size, works nicely as a small desktop app and would love to use the YT music app in this way 💯

**Comment by jordyvandomselaar** [comment]
Ah, my screenshot is of the music app, but you'd like to go even smaller :) makes sense!
