### ISSUE TITLE
Add AdBlock support

### ISSUE THREAD

**Issue by richardtop** [steve228uk/YouTube-Music#51]
It would be a fantastic app if the AdBlock extension could be installed.

**Comment by AvinashChowdary** [comment]
It might be more popular that actual youtube music if you do it.

**Comment by jdmartins** [comment]
Meanwhile you can block the `doubleclick` stuff on your `hosts` file to remove the ads
Check this [link](http://forums.radioreference.com/threads/block-google-and-f-book-crap-using-your-hosts-file.269946/)

**Comment by bro0k** [comment]
#68

**Comment by weyderfs** [comment]
Because instead of wanting ADBlock does not subscribe to YT Premium?
It's cheap.

**Comment by weyderfs** [comment]
Ok, use free but with Ads... \o/

**Comment by bendschs** [comment]
i was wondering if it ist possible to make such an about on the base of brave browser (https://github.com/brave/brave-browser). It automatically blocks ads if you turn the "shields" on.

cheers
bendsch
