### ISSUE TITLE
Next/Previous Media Control buttons not functioning in MacBook Air running 10.14.6

### ISSUE THREAD

**Issue by dinukapj** [steve228uk/YouTube-Music#78]
I love the app! The media control buttons for next/previous aren't functioning though. Play/Pause works, however.

**Comment by quentinlasco** [comment]
Me too on MacBook Pro 16 inches ! Please do something 🙂Thank you so much

**Comment by ZeusFSX** [comment]
On Mac OS 10.15.2 also not working!

**Comment by bruno-robert** [comment]
I also have this issue on a Macbook Pro running macOS 10.14.6 (both a 2013 and a 2015 model) as well as on an iMac running Catalina.

**Comment by sfla** [comment]
When clicking the next/previous buttons, nothing happens. But if I press and hold, it will fast forward/backward. Which is not what I want. I also want it to go to the next/previous song when clicking.

**Comment by bret-knight87** [comment]
I'm having the same thing on an iMac(2017) running 10.15.3. It's odd because they do work occasionally. Most of the time it's only the play/pause button that works.

**Comment by batwolf** [comment]
Same issue, Macbook Pro 16inch

**Comment by stephenfourie** [comment]
Same issue. Macbook pro 13 2015, running Catalina 10.15.3.
YT Music Version 1.0.6 (8)
Play/Pause works, and press and hold next/prev does fast forward/backward.

**Comment by Dolly-Ye** [comment]
Same MacBook Pro (15-inch, 2019)
Catalina 10.15.4.

**Comment by bmargula** [comment]
Same problem here

**Comment by ryj5566** [comment]
Same issue.
Macbook pro 13 2019
Catalina 10.15.5

**Comment by Marcel2508** [comment]
Any updates on this?

**Comment by wocar** [comment]
Same here :( I guess someone other than the owner would have to fix this.

**Comment by wocar** [comment]
https://www.bountysource.com/issues/85437501-next-previous-media-control-buttons-not-functioning-in-macbook-air-running-10-14-6?show_profile_modal=1

**Comment by wocar** [comment]
Maybe we can all chip in and get this fixed

**Comment by tobi512** [comment]
Same problem with MBP 16" and Magic Keyboard (bluetooth)

**Comment by emeren** [comment]
Same problem.. only skip song button missing.. !

**Comment by LunaticoCR** [comment]
Same here. MacMook Pro 15-inch 2018 and macOS 10.15.7. This was raised over a year ago, I would have thought a bug like this on one of the main features of this app would have been fixed by now. Is this project being maintained?

**Comment by TimOliver** [comment]
This is a duplicate of #33 so I'm going to close this issue in favour of continuing the discussion there. Thanks! :)
